/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SeoSchema = {
  _type: "seoSchema";
  serviceName?: string;
  serviceDescription?: string;
  serviceType?: string;
  areaServed?: string;
  offerCatalogName?: string;
  offers?: Array<{
    name: string;
    description: string;
    _key: string;
  }>;
  faqs?: Array<{
    question: string;
    answer: string;
    _key: string;
  }>;
  jsonLdPageLevelOverride?: string;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  publishDate?: string;
  openGraph?: {
    ogTitle?: string;
    ogDescription?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    ogType?: "website" | "article" | "profile";
  };
  twitterCard?: {
    tcTitle?: string;
    tcDescription?: string;
    tcImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    tcCard?: "summary" | "summary_large_image" | "app" | "player";
  };
  robotsSettings?: {
    noIndex?: boolean;
    noFollow?: boolean;
  };
};

export type Link = {
  _type: "link";
  label?: string;
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  externalUrl?: string;
};

export type NavItem = {
  _type: "navItem";
  type?: "dropdown" | "link";
  label: string;
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  externalUrl?: string;
  children?: Array<{
    _key: string;
  } & Link>;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type Faqs = {
  _type: "faqs";
  title?: string;
  description?: BlockContent;
  questions?: Array<{
    question: string;
    answer: string;
    _key: string;
  }>;
};

export type Testimonial = {
  _type: "testimonial";
  title?: string;
  viewAllReviews: Link;
  testimonials?: Array<{
    author: string;
    details?: string;
    review: number;
    _key: string;
  }>;
};

export type Banners = {
  _type: "banners";
  banner?: Array<{
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    link: Link;
    _key: string;
  }>;
};

export type QuickDelivery = {
  _type: "quickDelivery";
  title?: string;
  subtitle?: string;
  banners?: Array<{
    title?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    link: Link;
    _key: string;
  }>;
  deliveryText?: string;
};

export type ProductsSection = {
  _type: "productsSection";
  title?: string;
  viewAllLink?: Link;
  products?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
};

export type CategoryIconList = {
  _type: "categoryIconList";
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
};

export type HeroBanner = {
  _type: "heroBanner";
  leftBanner?: {
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    link: Link;
  };
  rightBanner?: {
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    link: Link;
  };
};

export type PageBuilder = Array<{
  _key: string;
} & HeroBanner | {
  _key: string;
} & CategoryIconList | {
  _key: string;
} & ProductsSection | {
  _key: string;
} & QuickDelivery | {
  _key: string;
} & Banners | {
  _key: string;
} & Testimonial | {
  _key: string;
} & Faqs>;

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  productCategory: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  description: BlockContent;
  price: number;
  isOutOfStock: boolean;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  statement1?: string;
  statement2?: string;
  navigation?: Array<{
    _key: string;
  } & NavItem>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  categoryType: "parent" | "child";
  parent?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  headerContent?: string;
  footerContent?: string;
  icon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seo?: Seo;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sections?: PageBuilder;
  seo?: Seo;
  seoSchema?: SeoSchema;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SeoSchema | Seo | Link | NavItem | BlockContent | Faqs | Testimonial | Banners | QuickDelivery | ProductsSection | CategoryIconList | HeroBanner | PageBuilder | Product | SanityImageCrop | SanityImageHotspot | Slug | Footer | Category | Homepage | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/lib/queries/index.ts
// Variable: HomePageQuery
// Query: *[_type == "homepage"][0]{    _id,      sections[]{    _type,    _key,        _type == "heroBanner" => {      leftBanner {        image,        link {            label,  linkType,  internalLink->{ slug { current } },  externalUrl        }      },      rightBanner {        image,        link {            label,  linkType,  internalLink->{ slug { current } },  externalUrl        }      }    },        _type == "categoryIconList" => {     categories[]->{       name,       slug,     }    },        _type == "productsSection" => {      title,      viewAllLink {          label,  linkType,  internalLink->{ slug { current } },  externalUrl      },      products[]->{        _id,        price,        name,        "slug": slug.current,        images      }    },        _type == "quickDelivery" => {      title,      subtitle,      deliveryText,      banners[]{        title,        image,        link {            label,  linkType,  internalLink->{ slug { current } },  externalUrl        }      }    },        _type == "banners" => {        banner[]{          image,          link {              label,  linkType,  internalLink->{ slug { current } },  externalUrl          }        }    },         _type == "testimonial" => {        title,        viewAllReviews {            label,  linkType,  internalLink->{ slug { current } },  externalUrl        },        testimonials[]{          _key,          author,          details,          review        }    },        _type == "faqs" => {        description[],        questions[]{          _key,          question,          answer        }    }  }    // TODO: Add seo and schema  }
export type HomePageQueryResult = {
  _id: string;
  sections: Array<{
    _type: "banners";
    _key: string;
    banner: Array<{
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      link: {
        label: string | null;
        linkType: "external" | "internal" | null;
        internalLink: {
          slug: {
            current: string;
          };
        } | null;
        externalUrl: string | null;
      };
    }> | null;
  } | {
    _type: "categoryIconList";
    _key: string;
    categories: Array<{
      name: string;
      slug: Slug;
    }> | null;
  } | {
    _type: "faqs";
    _key: string;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }> | null;
    questions: Array<{
      _key: string;
      question: string;
      answer: string;
    }> | null;
  } | {
    _type: "heroBanner";
    _key: string;
    leftBanner: {
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      link: {
        label: string | null;
        linkType: "external" | "internal" | null;
        internalLink: {
          slug: {
            current: string;
          };
        } | null;
        externalUrl: string | null;
      };
    } | null;
    rightBanner: {
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      link: {
        label: string | null;
        linkType: "external" | "internal" | null;
        internalLink: {
          slug: {
            current: string;
          };
        } | null;
        externalUrl: string | null;
      };
    } | null;
  } | {
    _type: "productsSection";
    _key: string;
    title: string | null;
    viewAllLink: {
      label: string | null;
      linkType: "external" | "internal" | null;
      internalLink: {
        slug: {
          current: string;
        };
      } | null;
      externalUrl: string | null;
    } | null;
    products: Array<{
      _id: string;
      price: number;
      name: string;
      slug: string;
      images: Array<{
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }> | null;
    }> | null;
  } | {
    _type: "quickDelivery";
    _key: string;
    title: string | null;
    subtitle: string | null;
    deliveryText: string | null;
    banners: Array<{
      title: string | null;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      link: {
        label: string | null;
        linkType: "external" | "internal" | null;
        internalLink: {
          slug: {
            current: string;
          };
        } | null;
        externalUrl: string | null;
      };
    }> | null;
  } | {
    _type: "testimonial";
    _key: string;
    title: string | null;
    viewAllReviews: {
      label: string | null;
      linkType: "external" | "internal" | null;
      internalLink: {
        slug: {
          current: string;
        };
      } | null;
      externalUrl: string | null;
    };
    testimonials: Array<{
      _key: string;
      author: string;
      details: string | null;
      review: number;
    }> | null;
  }> | null;
} | null;
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && categoryType == "parent"] | order(name asc) {    name,    "slug": slug.current,    "children": *[_type == "category" && categoryType == "child" && parent._ref == ^._id] | order(name asc) {      name,      "slug": slug.current    }  }
export type CATEGORIES_QUERYResult = Array<{
  name: string;
  slug: string;
  children: Array<{
    name: string;
    slug: string;
  }>;
}>;
// Variable: FOOTER_QUERY
// Query: *[_type == "footer"][0] {    statement1,    statement2,    navigation[] {      ...,      children[] {        ...,          label,  linkType,  internalLink->{ slug { current } },  externalUrl      },        label,  linkType,  internalLink->{ slug { current } },  externalUrl    },  }
export type FOOTER_QUERYResult = {
  statement1: string | null;
  statement2: string | null;
  navigation: Array<{
    _key: string;
    _type: "navItem";
    type?: "dropdown" | "link";
    label: string;
    linkType: "external" | "internal" | null;
    internalLink: {
      slug: {
        current: string;
      };
    } | null;
    externalUrl: string | null;
    children: Array<{
      _key: string;
      _type: "link";
      label: string | null;
      linkType: "external" | "internal" | null;
      internalLink: {
        slug: {
          current: string;
        };
      } | null;
      externalUrl: string | null;
    }> | null;
  }> | null;
} | null;
// Variable: PRODUCT_LISTING_QUERY
// Query: {  "products":  *[_type == "product" && $categorySlug in productCategory[]->slug.current && (    $filter == "" ||     ($filter == "price_above_200" && price > 200) ||     ($filter == "price_below_200" && price < 200) ||     ($filter == "out_of_stock" && isOutOfStock == true) ||     ($filter == "in_stock" && isOutOfStock == false)  )]    | order(_createdAt desc)[$start...$end]{      _id,      name,      slug,      price,      images,    },  "totalProducts": count(*[_type == "product" && $categorySlug in productCategory[]->slug.current && (   $filter == "" ||     ($filter == "price_above_200" && price > 200) ||     ($filter == "price_below_200" && price < 200) ||     ($filter == "out_of_stock" && isOutOfStock == true) ||     ($filter == "in_stock" && isOutOfStock == false)  )]),  "category": *[_type == "category" && slug.current == $categorySlug][0]{    name,    slug,    headerContent,    footerContent,  }}
export type PRODUCT_LISTING_QUERYResult = {
  products: Array<{
    _id: string;
    name: string;
    slug: Slug;
    price: number;
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }> | null;
  }>;
  totalProducts: number;
  category: {
    name: string;
    slug: Slug;
    headerContent: string | null;
    footerContent: string | null;
  } | null;
};
// Variable: PRODUCT_DETAIL_QUERY
// Query: *[_type == "product" && slug.current == $productSlug][0]{    ...,    productCategory[]->{      name,      slug    }  }
export type PRODUCT_DETAIL_QUERYResult = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  productCategory: Array<{
    name: string;
    slug: Slug;
  }>;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  description: BlockContent;
  price: number;
  isOutOfStock: boolean;
  seo?: Seo;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"homepage\"][0]{\n    _id,\n    \n  sections[]{\n    _type,\n    _key,\n    \n    _type == \"heroBanner\" => {\n      leftBanner {\n        image,\n        link {\n          \n  label,\n  linkType,\n  internalLink->{ slug { current } },\n  externalUrl\n\n        }\n      },\n      rightBanner {\n        image,\n        link {\n          \n  label,\n  linkType,\n  internalLink->{ slug { current } },\n  externalUrl\n\n        }\n      }\n    }\n,\n    \n    _type == \"categoryIconList\" => {\n     categories[]->{\n       name,\n       slug,\n     }\n    }\n,\n    \n    _type == \"productsSection\" => {\n      title,\n      viewAllLink {\n        \n  label,\n  linkType,\n  internalLink->{ slug { current } },\n  externalUrl\n\n      },\n      products[]->{\n        _id,\n        price,\n        name,\n        \"slug\": slug.current,\n        images\n      }\n    }\n\n,\n    \n    _type == \"quickDelivery\" => {\n      title,\n      subtitle,\n      deliveryText,\n      banners[]{\n        title,\n        image,\n        link {\n          \n  label,\n  linkType,\n  internalLink->{ slug { current } },\n  externalUrl\n\n        }\n      }\n    }\n,\n    \n    _type == \"banners\" => {\n        banner[]{\n          image,\n          link {\n            \n  label,\n  linkType,\n  internalLink->{ slug { current } },\n  externalUrl\n\n          }\n        }\n    }\n,\n    \n     _type == \"testimonial\" => {\n        title,\n        viewAllReviews {\n          \n  label,\n  linkType,\n  internalLink->{ slug { current } },\n  externalUrl\n\n        },\n        testimonials[]{\n          _key,\n          author,\n          details,\n          review\n        }\n    }\n,\n    \n    _type == \"faqs\" => {\n        description[],\n        questions[]{\n          _key,\n          question,\n          answer\n        }\n    }\n\n  }\n\n    // TODO: Add seo and schema\n  }\n": HomePageQueryResult;
    "\n  *[_type == \"category\" && categoryType == \"parent\"] | order(name asc) {\n    name,\n    \"slug\": slug.current,\n    \"children\": *[_type == \"category\" && categoryType == \"child\" && parent._ref == ^._id] | order(name asc) {\n      name,\n      \"slug\": slug.current\n    }\n  }\n": CATEGORIES_QUERYResult;
    "\n  *[_type == \"footer\"][0] {\n    statement1,\n    statement2,\n    navigation[] {\n      ...,\n      children[] {\n        ...,\n        \n  label,\n  linkType,\n  internalLink->{ slug { current } },\n  externalUrl\n\n      },\n      \n  label,\n  linkType,\n  internalLink->{ slug { current } },\n  externalUrl\n\n    },\n  }\n": FOOTER_QUERYResult;
    "{\n  \"products\": \n *[_type == \"product\" && $categorySlug in productCategory[]->slug.current && (\n    $filter == \"\" || \n    ($filter == \"price_above_200\" && price > 200) || \n    ($filter == \"price_below_200\" && price < 200) || \n    ($filter == \"out_of_stock\" && isOutOfStock == true) || \n    ($filter == \"in_stock\" && isOutOfStock == false)\n  )]\n    | order(_createdAt desc)[$start...$end]{\n      _id,\n      name,\n      slug,\n      price,\n      images,\n    }\n,\n  \"totalProducts\": count(*[_type == \"product\" && $categorySlug in productCategory[]->slug.current && (\n   $filter == \"\" || \n    ($filter == \"price_above_200\" && price > 200) || \n    ($filter == \"price_below_200\" && price < 200) || \n    ($filter == \"out_of_stock\" && isOutOfStock == true) || \n    ($filter == \"in_stock\" && isOutOfStock == false)\n  )]),\n  \"category\": *[_type == \"category\" && slug.current == $categorySlug][0]{\n    name,\n    slug,\n    headerContent,\n    footerContent,\n  }\n}": PRODUCT_LISTING_QUERYResult;
    "*[_type == \"product\" && slug.current == $productSlug][0]{\n    ...,\n    productCategory[]->{\n      name,\n      slug\n    }\n  }": PRODUCT_DETAIL_QUERYResult;
  }
}
